# Generated by Django 6.0.4 on 2026-04-17 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '001 initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
